name: docker-build
run-name: ${{ github.actor }} is building a docker image

on:
  push:
    branches:
      - 'main'

jobs:
  build-it:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Docker login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: ./buildit
